version: '3.8'

services:
  app-agenda:
    image: nodensx/examen-agenda:latest
    ports:
      # Usamos el puerto 5005 para que no choque con tus otros proyectos
      - "5005:5000"
    environment:
      # IMPORTANTE: Aquí conectamos la App con el servicio de abajo 'db-agenda'
      - DATABASE_URL=postgresql://user_agenda:pass_agenda@db-agenda:5432/db_agenda
    networks:
      - examen_drwm_agendatec
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  db-agenda:
    image: postgres:13
    environment:
      - POSTGRES_USER=user_agenda
      - POSTGRES_PASSWORD=pass_agenda
      - POSTGRES_DB=db_agenda
    networks:
      - examen_drwm_agendatec
    deploy:
      placement:
        constraints:
          # Esto cumple con tu requisito de que se aloje en el worker-1
          - node.hostname == worker-1

networks:
  # Definimos la red como externa porque ya la creaste manualmente en el Swarm
  examen_drwm_agendatec:
    external: true
